BEGIN TRANSACTION;

CREATE TABLE Emails
(
	EmailId INTEGER PRIMARY KEY AUTOINCREMENT,
	CreateDate DATETIME DEFAULT CURRENT_TIMESTAMP,
	ReceiverCharacterId INT NOT NULL,
	SenderCharacterId INT,
	SenderName TEXT NOT NULL,
	IsRead INT DEFAULT(0),
	Folder TEXT NOT NULL,
	Subject TEXT NOT NULL,
	Message TEXT NOT NULL
);

COMMIT;
